spring:
  datasource:
#    url: jdbc:mysql://rm-uf63m4yauotn1pz32o.mysql.rds.aliyuncs.com:3306/loafer?useSSL=false
    url: jdbc:mysql://localhost:3306/loafer?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
#    password: wuyuexin@1992
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
logging:
  level:
    root: info